// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTAqUfJql1zsSSNVob-oE9PaZYY9C3NX4',
    appId: '1:295901224317:web:6ded545e742b29fde7c014',
    messagingSenderId: '295901224317',
    projectId: 'mybus-a6ff8',
    authDomain: 'mybus-a6ff8.firebaseapp.com',
    storageBucket: 'mybus-a6ff8.firebasestorage.app',
    measurementId: 'G-GMDCEHM4RM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTD8GQFgot9D_yMP9Rx9Au1HNqFcQ7dx4',
    appId: '1:295901224317:android:d367c1a8662f4828e7c014',
    messagingSenderId: '295901224317',
    projectId: 'mybus-a6ff8',
    storageBucket: 'mybus-a6ff8.firebasestorage.app',
  );

}